//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodeNamesBDEntities : DbContext
    {
        public CodeNamesBDEntities()
            : base("name=CodeNamesBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> PlayerSet { get; set; }
        public virtual DbSet<FriendshipRequest> FriendshipRequestSet { get; set; }
        public virtual DbSet<Friendship> FriendshipSet { get; set; }
    }
}
