//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int IdFriendship { get; set; }
        public int IdPlayer1 { get; set; }
        public int IdPlayer2 { get; set; }
    
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
    }
}
